/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FundamentosPoo5C.tercerParcial;

/**
 *
 * @author ruth_
 */
public class InterfacePrueba extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePrueba
     */
    public InterfacePrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCharacters = new javax.swing.JLabel();
        labelinstruction = new javax.swing.JLabel();
        labelPicture = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pergamino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel labelBackground = new javax.swing.JLabel();
        btVillager1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCharacters.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        labelCharacters.setText("CHARACTERS");
        getContentPane().add(labelCharacters, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        labelinstruction.setText("Select a Character!");
        getContentPane().add(labelinstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        labelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundamentosPoo5C/tercerParcial/1reyResized.jpg"))); // NOI18N
        getContentPane().add(labelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jList1.setBackground(new java.awt.Color(215, 193, 151));
        jList1.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "  KING", " ", "  NOBLE", " ", "  NOBLE", " ", "  COUNT", " ", "  COUNT", " ", "  BARON", " ", "  BARON", " ", "  DUKE", " ", "  DUKE", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  MUSICIAN", " ", "  MUSICIAN", " ", "  MUSICIAN", " ", "  JESTER", " ", "  JESTER", " ", "  JESTER" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 530));

        pergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundamentosPoo5C/tercerParcial/characters (3).png"))); // NOI18N
        pergamino.setText("jLabel1");
        getContentPane().add(pergamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundamentosPoo5C/tercerParcial/pictureBakcground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 390, 390));

        labelBackground.setBackground(new java.awt.Color(0, 0, 0));
        labelBackground.setForeground(new java.awt.Color(187, 162, 113));
        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundamentosPoo5C/tercerParcial/background2.png"))); // NOI18N
        getContentPane().add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 950));

        btVillager1.setText("Villager 1");
        getContentPane().add(btVillager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVillager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCharacters;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JLabel labelinstruction;
    private javax.swing.JLabel pergamino;
    // End of variables declaration//GEN-END:variables
}
