/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceProyecto;

/**
 *
 * @author ruth_
 */
public class InterfacePrueba extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePrueba
     */
    public InterfacePrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCharacters = new javax.swing.JLabel();
        labelinstruction = new javax.swing.JLabel();
        labelPicture = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        labelFlag = new javax.swing.JLabel();
        pergamino = new javax.swing.JLabel();
        labelInputDescription = new javax.swing.JLabel();
        laberlDescription = new javax.swing.JLabel();
        labelInputName = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelCharacter = new javax.swing.JLabel();
        labelKingdomName = new javax.swing.JLabel();
        labelLocationInput = new javax.swing.JLabel();
        labelCurrencyInput = new javax.swing.JLabel();
        labelDecreeInput = new javax.swing.JLabel();
        labelAlliedKInput = new javax.swing.JLabel();
        labelAlliedKingdom = new javax.swing.JLabel();
        labelDecrees = new javax.swing.JLabel();
        labelcurrency = new javax.swing.JLabel();
        labelLocation = new javax.swing.JLabel();
        labelFlagBackground = new javax.swing.JLabel();
        labeloutput = new javax.swing.JLabel();
        outputBackground = new javax.swing.JLabel();
        btPayTaxes = new javax.swing.JButton();
        btCommandLowerClass = new javax.swing.JButton();
        labelUpperCLass = new javax.swing.JLabel();
        labelDarkMode = new javax.swing.JLabel();
        btUnearthSword = new javax.swing.JButton();
        btInheritThrone = new javax.swing.JButton();
        btBetrayKingdom = new javax.swing.JButton();
        RbtDarkMode = new javax.swing.JRadioButton();
        RbtPlague = new javax.swing.JRadioButton();
        labelPlague = new javax.swing.JLabel();
        labelInstructionsActions1 = new javax.swing.JLabel();
        btBanish = new javax.swing.JButton();
        labelInstructionSpecial = new javax.swing.JLabel();
        labelUpperCLasInstructions = new javax.swing.JLabel();
        labelInstructionKing1 = new javax.swing.JLabel();
        btPlay = new javax.swing.JButton();
        btEntretain = new javax.swing.JButton();
        btUseTool = new javax.swing.JButton();
        btAttack = new javax.swing.JButton();
        labelSpecialActions = new javax.swing.JLabel();
        labelKingsActions = new javax.swing.JLabel();
        btMakeDecree = new javax.swing.JButton();
        labelActions = new javax.swing.JLabel();
        javax.swing.JLabel labelBackground = new javax.swing.JLabel();
        btVillager1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelCharacters.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        labelCharacters.setText("CHARACTERS");
        labelCharacters.setBounds(100, 200, -1, -1);
        getContentPane().add(labelCharacters);

        labelinstruction.setText("Select a Character!");
        labelinstruction.setBounds(110, 240, -1, -1);
        getContentPane().add(labelinstruction);

        labelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/1reyResized.jpg")));
        labelPicture.setBounds(390, 150, -1, -1);// NOI18N
        getContentPane().add(labelPicture);

        jList1.setBackground(new java.awt.Color(215, 190, 157));
        jList1.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "  KING", " ", "  NOBLE", " ", "  NOBLE", " ", "  COUNT", " ", "  COUNT", " ", "  BARON", " ", "  BARON", " ", "  DUKE", " ", "  DUKE", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  VILLAGER", " ", "  MUSICIAN", " ", "  MUSICIAN", " ", "  MUSICIAN", " ", "  JESTER", " ", "  JESTER", " ", "  JESTER" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);

        labelFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/Flag.png"))); // NOI18N
        getContentPane().add(labelFlag);

        pergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/characters (3).png"))); // NOI18N
        pergamino.setText("jLabel1");
        getContentPane().add(pergamino);

        labelInputDescription.setText("description");
        getContentPane().add(labelInputDescription);

        laberlDescription.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        laberlDescription.setText("DESCRIPTION");
        getContentPane().add(laberlDescription);

        labelInputName.setText("name");
        getContentPane().add(labelInputName);

        labelName.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        labelName.setText("NAME");
        getContentPane().add(labelName);

        labelCharacter.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/pictureBackground.png")));
        labelCharacter.setBounds(330, 40, 480, 355);// NOI18N
        getContentPane().add(labelCharacter);

        labelKingdomName.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        labelKingdomName.setText("Dark Citadel Kingdom");
        getContentPane().add(labelKingdomName);

        labelLocationInput.setText("location");
        getContentPane().add(labelLocationInput);

        labelCurrencyInput.setText("currency");
        getContentPane().add(labelCurrencyInput);

        labelDecreeInput.setText("decrees");
        getContentPane().add(labelDecreeInput);

        labelAlliedKInput.setText("allied kingdoms");
        getContentPane().add(labelAlliedKInput);

        labelAlliedKingdom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAlliedKingdom.setText("Allied Kingdoms:");
        getContentPane().add(labelAlliedKingdom);

        labelDecrees.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelDecrees.setText("Decress:");
        getContentPane().add(labelDecrees);

        labelcurrency.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelcurrency.setText("Currency:");
        getContentPane().add(labelcurrency);

        labelLocation.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelLocation.setText("Location:");
        getContentPane().add(labelLocation);

        labelFlagBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/FlagBackground.png")));
        labelFlagBackground.setBounds(850, 80, 610, 269);// NOI18N
        getContentPane().add(labelFlagBackground);

        labeloutput.setText("OUTPUT");
        getContentPane().add(labeloutput);

        outputBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/FlagBackground.png"))); // NOI18N
        outputBackground.setBounds(1180, 700, 410, 210);
        getContentPane().add(outputBackground);

        btPayTaxes.setText("Pay Taxes");
        btPayTaxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPayTaxesActionPerformed(evt);
            }
        });
        getContentPane().add(btPayTaxes);

        btCommandLowerClass.setText("Command Lower Class");
        btCommandLowerClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommandLowerClassActionPerformed(evt);
            }
        });
        getContentPane().add(btCommandLowerClass);

        labelUpperCLass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelUpperCLass.setText("Upper Class Actions");
        getContentPane().add(labelUpperCLass);

        labelDarkMode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelDarkMode.setText("Dark Mode");
        getContentPane().add(labelDarkMode);

        btUnearthSword.setText("Unearth Sword");
        getContentPane().add(btUnearthSword);

        btInheritThrone.setText("Inherit Throne");
        getContentPane().add(btInheritThrone);

        btBetrayKingdom.setText("Betray Kingdom");
        getContentPane().add(btBetrayKingdom);

        RbtDarkMode.setText("Find out who are werewolves and witches in the kingdom");
        getContentPane().add(RbtDarkMode);

        RbtPlague.setText("Show who has the plague");
        getContentPane().add(RbtPlague);

        labelPlague.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelPlague.setText("Plague");
        getContentPane().add(labelPlague);

        labelInstructionsActions1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelInstructionsActions1.setText("Select a character, click on the different icons and find out what happens!");
        getContentPane().add(labelInstructionsActions1);

        btBanish.setText("Banish");
        getContentPane().add(btBanish);

        labelInstructionSpecial.setText("Find out who can perform the special actions!");
        getContentPane().add(labelInstructionSpecial);

        labelUpperCLasInstructions.setText("Actions that only the upper class can perform");
        getContentPane().add(labelUpperCLasInstructions);

        labelInstructionKing1.setText("Actions only the King can perform");
        getContentPane().add(labelInstructionKing1);

        btPlay.setText("Play");
        getContentPane().add(btPlay);

        btEntretain.setText("Entretain");
        getContentPane().add(btEntretain);

        btUseTool.setText("Use Tool");
        getContentPane().add(btUseTool);

        btAttack.setText("Attack");
        getContentPane().add(btAttack);

        labelSpecialActions.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelSpecialActions.setText("Special Actions");
        getContentPane().add(labelSpecialActions);

        labelKingsActions.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelKingsActions.setText("King's Actions");
        getContentPane().add(labelKingsActions);

        btMakeDecree.setText("Make Decree");
        getContentPane().add(btMakeDecree);

        labelActions.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/actions.png")));
        labelActions.setBounds(380, 410, 1086, 440);// NOI18N
        getContentPane().add(labelActions);

        labelBackground.setBackground(new java.awt.Color(0, 0, 0));
        labelBackground.setForeground(new java.awt.Color(187, 162, 113));
        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagenesPoo/background.png")));
        labelBackground.setBounds(0, 0, 1590, 950);
        // NOI18N
        getContentPane().add(labelBackground);

        btVillager1.setText("Villager 1");
        getContentPane().add(btVillager1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPayTaxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPayTaxesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPayTaxesActionPerformed

    private void btCommandLowerClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommandLowerClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCommandLowerClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtDarkMode;
    private javax.swing.JRadioButton RbtPlague;
    private javax.swing.JButton btAttack;
    private javax.swing.JButton btBanish;
    private javax.swing.JButton btBetrayKingdom;
    private javax.swing.JButton btCommandLowerClass;
    private javax.swing.JButton btEntretain;
    private javax.swing.JButton btInheritThrone;
    private javax.swing.JButton btMakeDecree;
    private javax.swing.JButton btPayTaxes;
    private javax.swing.JButton btPlay;
    private javax.swing.JButton btUnearthSword;
    private javax.swing.JButton btUseTool;
    private javax.swing.JButton btVillager1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelActions;
    private javax.swing.JLabel labelAlliedKInput;
    private javax.swing.JLabel labelAlliedKingdom;
    private javax.swing.JLabel labelCharacter;
    private javax.swing.JLabel labelCharacters;
    private javax.swing.JLabel labelCurrencyInput;
    private javax.swing.JLabel labelDarkMode;
    private javax.swing.JLabel labelDecreeInput;
    private javax.swing.JLabel labelDecrees;
    private javax.swing.JLabel labelFlag;
    private javax.swing.JLabel labelFlagBackground;
    private javax.swing.JLabel labelInputDescription;
    private javax.swing.JLabel labelInputName;
    private javax.swing.JLabel labelInstructionKing1;
    private javax.swing.JLabel labelInstructionSpecial;
    private javax.swing.JLabel labelInstructionsActions1;
    private javax.swing.JLabel labelKingdomName;
    private javax.swing.JLabel labelKingsActions;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelLocationInput;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JLabel labelPlague;
    private javax.swing.JLabel labelSpecialActions;
    private javax.swing.JLabel labelUpperCLasInstructions;
    private javax.swing.JLabel labelUpperCLass;
    private javax.swing.JLabel labelcurrency;
    private javax.swing.JLabel labelinstruction;
    private javax.swing.JLabel labeloutput;
    private javax.swing.JLabel laberlDescription;
    private javax.swing.JLabel outputBackground;
    private javax.swing.JLabel pergamino;
    // End of variables declaration//GEN-END:variables
}
